### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by stonegray** [stonegray/plugin-detect#1]
An unhandled error occured in the application. I am running version 0.0.2 using Node v15.2.0. The error is automatically added below. Please add a brief description of the problem and a title. 

This is a test of the auto reporting thing

Error:
```
Foobarf
```
Stack:
```
Error: Foobarf
    at getPlugins (file:///Users/stonegray/Documents/Work/Personal/PersonalProjects/plugin-detect/src/index.js:31:9)
    at file:///Users/stonegray/Documents/Work/Personal/PersonalProjects/plugin-detect/example/example.js:3:23
    at ModuleJob.run (node:internal/modules/esm/module_job:146:23)
    at async Loader.import (node:internal/modules/esm/loader:165:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)```

**Comment by stonegray** [comment]
Looks good!
