### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by stonegray** [stonegray/plugin-detect#3]
An unhandled error occured in the application. I am running version 0.0.4 using Node v19.4.0. The error is automatically added below. Please add a brief description of the problem and a title. 

Error:
```
Cannot read properties of null (reading 'nodeName')
```
Stack:
```
TypeError: Cannot read properties of null (reading 'nodeName')
    at Object.parse (/Users/stonegray/git/plugin-detect/node_modules/plist/lib/parse.js:68:25)
    at readPlistFile (file:///Users/stonegray/git/plugin-detect/src/util/readPlistFile.js:19:15)
    at async scanPlugin (file:///Users/stonegray/git/plugin-detect/src/scanPlugin.js:20:16)
    at async getUserPlugins (file:///Users/stonegray/git/plugin-detect/src/getUserPlugins.js:46:15)
    at async getPlugins (file:///Users/stonegray/git/plugin-detect/src/index.js:29:32)
    at async file:///Users/stonegray/git/plugin-detect/example/example.js:3:17```

**Comment by stonegray** [comment]
Fixed #4
